### ISSUE TITLE
Doesnt seem to do anything at all on my macbook air 2014

### ISSUE THREAD

**Issue by kitt3n** [dgraziotin/Fan-Control-Daemon#54]
I tried this out; it doesnt start the fan at all! The macfanctld fan control works super though.

**Comment by dgraziotin** [comment]
Hi, thank you for contacting.

Could you please provide more information?

What to the tests say?

What it the output of the -f -v flags?

**Comment by kitt3n** [comment]
I am running Linux Mint 17.1 with kernel 3.15 because anything higher than 3.15 makes the fan spin 100% because of a coret?) I reinstalled macfanctld when I noticed my SSD was at 77 celcius... 

~/Fan-Control-Daemon/bin $ sudo ./mbpfan -f -v
Writing a new .pid file with value 8692 at: /var/run/mbpfan.pid
mbpfan[8692]: Writing a new .pid file with value 8692 at: /var/run/mbpfan.pid
Successfully written a new .pid file with value 8692 at: /var/run/mbpfan.pid
mbpfan[8692]: Successfully written a new .pid file with value 8692 at: /var/run/mbpfan.pid
Couldn't open configfile, using defaults
Detected kernel version: 3
Detected kernel minor revision: 15
Using new sensor path for kernel >= 3.0.15
Found hwmon path at /sys/devices/platform/coretemp.0/hwmon/hwmon0/temp
Found 3 sensors
Found 1 fans
Sleeping for 2 seconds to get first temp delta
Old Temp 71: New Temp: 71, Fan Speed: 2000
Sleeping for 7 seconds
Old Temp 71: New Temp: 72, Fan Speed: 2420
Sleeping for 7 seconds
Old Temp 72: New Temp: 71, Fan Speed: 2420
Sleeping for 7 seconds
^MOld Temp 71: New Temp: 71, Fan Speed: 2420
Sleeping for 7 seconds

**Comment by dgraziotin** [comment]
Thank you very much. The -f -v output is perhaps too short for me to understand the issue completely.
I see that the fan speed was brought from 2000 rpms to 2420. I understand that with 72 degrees this is a too low number.

However, have you heard the fan increasing? 

What happens if you let mbpfan run for more than 30 seconds? I would need 60-90 seconds. Don't worry, it won't burn your macbook.

Another thing I noticed is that you have not installed the config file. Have you tried adjusting it to see if you could raise the fan speed?

Thanks!

**Comment by kitt3n** [comment]
This seems to be an issue with the service script now, when I run it for a while, it slows down the fan but keeps it going on at the same temperature...not sure about the configuration file though, but the default is alright for testing http://pastie.org/9865096 when I had it installed; it simply didnt seem to start at all, possibly the pid thing?

**Comment by kitt3n** [comment]
Can confirm the pid issue to be the problem for me. mbpfan did not start automatically on boot with the Ubuntu service file http://pastie.org/9867619 running it manually after removing the pid file worked though.

**Comment by dgraziotin** [comment]
Thank you very much for your reports. There has actually been a recent pull request, which might solve your issue. Could you please try compiling from master and see if that works for you?

Thanks

**Comment by kitt3n** [comment]
The pull request you merged fixed the start issue for me! :) I can also confirm that this works fine on Macbook Air 6,2 i5 4 gb.

**Comment by dgraziotin** [comment]
Brilliant! @marji, thank you so much for your pull request.
