### ISSUE TITLE
mbpfan service spam on boot about applesmc and other things

### ISSUE THREAD

**Issue by kitt3n** [dgraziotin/Fan-Control-Daemon#55]
I keep seeing this when linux mint boots up http://pastie.org/9885308 first with a (fail) message in red, then a bunch of mbpfan service messages, and the paste in the logs under /var/log/upstart/mbpfan.log

**Comment by philplckthun** [comment]
As there seems to be no one willing to answer this:

mbpfan doesn't work without the kernel modules: applesmc and coretemp.

Edit the “/etc/modules” file:

```sudo nano /etc/modules```

And add the following two lines:

```
coretemp
applesmc
```

Then reboot and it should work as expected.

**Comment by dgraziotin** [comment]
@philplckthun thank you so much for taking care of this.
@kitt3n that should really do the trick! I will update the README file to at least give a hint on how to load modules when booting GNU/Linux.

**Comment by kitt3n** [comment]
This seems to have done it, the fans were properly working before I had applesmc added to the modules list, but now the warnings are gone! Cheers :D
