### ISSUE TITLE
Control the fanspeed?

### ISSUE THREAD

**Issue by DonHansDampf** [dgraziotin/Fan-Control-Daemon#56]
Hey there!

You deamon works great, even on a MacBook Air 2013. But is there some way to manually controll the speed? At 70°C the fan still goes around 5000RPM. Even under MacOS it would run so fast at this point.

So is there a way to configure the deamon?

Thanks

**Comment by dgraziotin** [comment]
Hi,

You should be able to configure it using the file /etc/mbpfan.conf (see the default one [here](https://github.com/dgraziotin/Fan-Control-Daemon/blob/master/mbpfan.conf)). The file is [supposed to be copied there](https://github.com/dgraziotin/Fan-Control-Daemon/blob/master/Makefile#L65) when when you do a make install.

**Comment by DonHansDampf** [comment]
Hey,

thanks for the fast response. I used the AUR-Package on Arch and somehow overlooked the config-file. My bad. Sorry.

Greetings
