### ISSUE TITLE
Add a changelog file

### ISSUE THREAD

**Issue by Yamakaky** [dgraziotin/Fan-Control-Daemon#57]
Hi
Did you consider adding a changelog file to your repo ? See http://keepachangelog.com/.

**Comment by dgraziotin** [comment]
Hello,

Yes, I did. Unfortunately, I do not have the time to curate a nice changelog (but thank you for the link, I was not aware of this website). 

For the moment, I will keep using GitHub [Releases](https://github.com/dgraziotin/Fan-Control-Daemon/releases) with spare details, e.g., solved issues and some minimum notes.

Cheers!
